version: "3.5"

services:
  db_auth:
    container_name: db_auth
    image: postgres:15.5-alpine3.18
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
      POSTGRES_USER: ${USERNAME_POSTGRES}
      POSTGRES_DB: docker_auth
    volumes:
      - ./infrastructure/db/postgres-data:/var/lib/postgresql/data
